title: It's Ya Boiiiiii
author: Art
email: art@bueno.com
description: > # this means to ignore newlines until "baseurl:"
  Everything And Nothing At The Same Time

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
